# Generated by Django 2.1.1 on 2018-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymterion', '0002_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation_date'),
        ),
    ]
